# Generated by Django 5.2.7 on 2025-10-14 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255, verbose_name='Subject Name')),
                ('num_questions', models.IntegerField(verbose_name='Number of Questions')),
                ('num_options', models.IntegerField(verbose_name='Number of Options per Question')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectAnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(verbose_name='Correct Answers')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer_sheet', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Correct Answer Sheet',
                'verbose_name_plural': 'Correct Answer Sheets',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Sheet Code')),
                ('student_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Student Name')),
                ('student_answers', models.JSONField(blank=True, null=True, verbose_name='Student Answers')),
                ('correct_items', models.IntegerField(default=0, verbose_name='Correct Items')),
                ('incorrect_items', models.IntegerField(default=0, verbose_name='Incorrect Items')),
                ('accuracy_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Accuracy Percentage')),
                ('sheet_image', models.ImageField(blank=True, null=True, upload_to='student_answer_sheets/', verbose_name='Answer Sheet Image')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answer_sheets', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Student Answer Sheet',
                'verbose_name_plural': 'Student Answer Sheets',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
